name: Publish NPM Packages
on: workflow_dispatch
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: git config email
        run: git config --local user.email tiktokbot@users.noreply.github.com
      - name: git config name
        run: git config --local user.name tiktokbot
      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: node common/scripts/install-run-rush.js build --verbose
      - name: 'Rush version'
        run: node common/scripts/install-run-rush.js version --bump --version-policy none --target-branch ${{ github.ref_name }}
      - name: Rush publish
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch ${{ github.ref_name }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
