name: Publish NPM Packages
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          # No automatic version-bumping in the current workflow
          # token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: git config email
        run: git config --local user.email tiktokbot@users.noreply.github.com
      - name: git config name
        run: git config --local user.name tiktokbot
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish NPM package
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" >> .npmrc
          echo ----
          cat .npmrc
          echo ----
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
